### ISSUE TITLE
problem with installing itypescript

### ISSUE THREAD

**Issue by marefati110** [nearbydelta/itypescript#18]
when i want install itypescript package i get this erorr:

```
➜  ~ sudo npm install -g itypescript
[sudo] password for ali: 
/home/ali/bin/its -> /home/ali/lib/node_modules/itypescript/bin/itypescript.js
/home/ali/bin/itskernel -> /home/ali/lib/node_modules/itypescript/lib/kernel.js

> zeromq@4.6.0 install /home/ali/lib/node_modules/itypescript/node_modules/zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)


prebuild-install WARN install EACCES: permission denied, access '/home/ali/.npm'

internal/fs/utils.js:230
    throw err;
    ^

Error: EACCES: permission denied, mkdir '/home/ali/lib/node_modules/itypescript/node_modules/zeromq/zmq'
    at Object.mkdirSync (fs.js:840:3)
    at Object.<anonymous> (/home/ali/lib/node_modules/itypescript/node_modules/zeromq/scripts/preinstall.js:89:8)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/home/ali/lib/node_modules/itypescript/node_modules/zeromq/zmq'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq@4.6.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@4.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ali/.npm/_logs/2020-04-07T11_51_10_832Z-debug.log

```
node : v12
npm : v6
os : ubuntu18.04

**Comment by SHND** [comment]
try `npm install -g --unsafe-perm itypescript`
